MODEL:
  TYPE: vssm
  NAME: vssm_tiny_32
  DROP_PATH_RATE: 0.2
  VSSM:
    EMBED_DIM: 32
    DEPTHS: [ 2, 2, 2, 2 ]
    SSM_D_STATE: 1
    SSM_DT_RANK: "auto"
    SSM_RATIO: 1.0
    SSM_CONV: 3
    SSM_CONV_BIAS: false
    SSM_FORWARDTYPE: "v05_noz" # v3_noz
    MLP_RATIO: 4.0
    DOWNSAMPLE: "v1"
    PATCHEMBED: "v2"
    NORM_LAYER: "ln2d"
